esphome:
  name: monitorbacklight
  platform: ESP32
  board: esp32dev

  platformio_options:
    upload_speed: 115200
    lib_deps: 
      NeoPixelBus@2.5.6

  on_boot:
    then:
      - light.turn_on:
          id: monitorbacklight_led
          effect: warnings 
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Digitalwerkstatt Bme680"
    password: !secret wifi_ap_password
  
# captive_portal:
  
# Enable logging
logger:
  
# Enable Home Assistant API
api:
  password: !secret api_password
  
ota:
  password: !secret ota_password
  
light:
  - platform: neopixelbus
    type: GRB
    pin: GPIO5
    variant: WS2812
    num_leds: 100
    name: "Monitor Backlight"
    id: monitorbacklight_led
    effects:
      - addressable_rainbow:
          name: "rainbow"